import express from "express";
import expressJSDocSwagger from "express-jsdoc-swagger";

import { basicAuth } from "./middlewares/basic-auth";
// load the CRUD API spec from the JSON file generated by `zenstack`
import crudApiSpec from "./openapi.json";

const app = express();

// enable JSON body parser
app.use(express.json());

// Add gard before serving the API docs
// and load the static files from the swagger-ui-dist package
app.use(
  "/api-docs",
  basicAuth,
  express.static("node_modules/swagger-ui-dist/", { index: false }),
);

// options for loading the extra OpenAPI from JSDoc
const swaggerOptions = {
  info: {
    version: "0.1.0",
    title: "Minerva CT external API",
  },
  filesPattern: "../../express-api/src/index.ts", // scan app.ts for OpenAPI JSDoc
  baseDir: __dirname,
  servers: [
    {
      url: "http://localhost:8000",
      description: "Local server",
    },
  ],
  // URL where SwaggerUI will be rendered
  swaggerUIPath: "/api-docs",
  // Expose OpenAPI UI
  exposeSwaggerUI: true,
  // Expose Open API JSON Docs documentation in `apiDocsPath` path.
  exposeApiDocs: true,
  // Open API JSON Docs endpoint.
  apiDocsPath: "/api-docs", // serve the merged JSON specifcation at /api-docs
  // Bearer token authentication
  // security: {
  //   BearerAuth: {
  //     type: "http",
  //     scheme: "bearer",
  //   },
  // },
};

// merge two specs and serve the UI
expressJSDocSwagger(app)(swaggerOptions, crudApiSpec);

app.listen(3001, () =>
  console.log("🚀 Server ready at: http://localhost:3001"),
);
